config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  
  root 'users#my_portfolio'
  
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stocks', to: 'stocks#search'

end

app/models/stock.rb
class Stock < ActiveRecord::Base
  
  def self.find_by_ticker(ticker_symbol)

    where(ticker: ticker_symbol).first
  
  end
  
  def price
  
    closing_price = StockQuote::Stock.quote(ticker).close
    
    return "#{closing_price} (Closing)" if closing_price
    
    opening_price = StockQuote::Stock.quote(ticker).open
    
    return "#{opening_price} (Opening)" if opening_price
    
    'Unavailable'
  
  end
  
  def self.new_from_lookup(ticker_symbol)
  
    looked_up_stock = StockQuote::Stock.quote(ticker_symbol)
    
    return nil unless looked_up_stock.name
    
    new_stock = new(ticker: looked_up_stock.symbol, name: looked_up_stock.name)
    
    new_stock.last_price = new_stock.price
    
    new_stock
    
  end
  
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_action :authenticate_user!
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search
  
    if params[:stock]
    
      @stock = Stock.find_by_ticker(params[:stock])
      
      @stock ||= Stock.new_from_lookup(params[:stock])
    
    end
    
    if @stock
    
      render partial: 'lookup'
    
    else
    
      render status: :not_found, nothing: true
    
    end
  
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def my_portfolio
  
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinanceTracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stocks/_lookup.html.erb
<div id="stock-lookup">

  <h3>Search for Stocks</h3>
  
  <%= form_tag search_stocks_path, remote: true, method: :get, id: 'stock-lookup-form' do %>
  
    <div class="form-group row no-padding text-center col-md-12">
    
      <div class="col-md-10">
      
        <%= text_field_tag :stock, params[:stock], placeholder: 'Stock Ticker Symbol',
        
        autofocus: true, class: 'form-control search-box input-lg' %>
        
      </div>
      
      <div class="col-md-2">
      
        <%= button_tag(type: :submit, class: 'btn btn-lg btn-success') do %>
        
          <i class='fa fa-search'></i> Look up a stock
        
        <% end %>
      
      </div>
    
    </div>
    
    <% if @stock %>

      <div id="stock-lookup-results" class="well results-block">
      
        <strong>Symbol:</strong> <%= @stock.ticker %>
        
        <strong>Name:</strong> <%= @stock.name %>
        
        <strong>Price:</strong> <%= @stock.price %>
      
      </div>
    
    <% end %>
  
  <% end %>

</div>

app/views/users/my_portfolio.html.erb
<%= render 'stocks/lookup' %>

app/views/welcome/index.html.erb
 <h1>Welcome to the finance tracker app</h1>
 
 <%= link_to "logout", destroy_user_session_path, method: :delete %>